### ISSUE TITLE
Suggested improvement for alt text in Animated visualisation example

### ISSUE THREAD

**Issue by hturner** [numbats/alt-text-for-data-plots#4]
In the Animated visualisation example of `example.Rmd`, the alt text duplicates some information from the caption. 

Alt text

> Most of the voters remain in the same party where a small fraction of voters with roughly equal male-to-female ratio switch to other major parties such as Labor, Greens, and National. Some decided not to vote. People who identified themselves as other have all shifted to the Green Party.

Caption

> Most voters remain loyal to the party, but a small fraction of voters with roughly equal male-to-female ratio switch primarily to the other major party. Interestingly, the few individuals who identified as neither male nor female overwhelmingly shifted their party affiliations to the Greens.

Also, I'm not sure it is clear enough that the visualisation is only showing the change for liberal voters (rather than this being the main feature of interest).

Suggested update:

**Alt text:** An animated visualisation with s-curve shaded areas showing the flow of Liberal voters from 2016 to the various parties in 2019, with people [?] represented by dots coloured by their gender identification in the 2016 and 2019 surveys. There are three gender identifications, male, female, and other. Some Liberal voters did not to vote in 2019. 

["decided not to vote" suggests an active choice - there may be other factors that prevented them voting]

**Comment by KrisanatA** [comment]
Thank you for the suggestion. I have made changes to this. It makes sense that the alt text should not be repeated with what is already in the caption.
